Colibri/Colibri/Areas/Admin/Controllers/CategoryTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Colibri.Data;
using Colibri.Models;
using Colibri.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Colibri.Areas.Admin.Controllers
{
    // authorize only the SuperAdminEndUser
    [Authorize(Roles = StaticDetails.SuperAdminEndUser)]
    [Area("Admin")]
    public class CategoryTypesController : Controller
    {
        private ColibriDbContext _colibriDbContext;

        public CategoryTypesController(ColibriDbContext colibriDbContext)
        {
            _colibriDbContext = colibriDbContext;
        }

        // Get: /<controller>/Create
        public IActionResult Create()
        {
            return View();
        }

        // Post: /<controller>/Create
        // @param Category
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryTypes categoryTypes)
        {
            // Check the State Model Binding
            if (ModelState.IsValid)
            {
                _colibriDbContext.Add(categoryTypes);
                await _colibriDbContext.SaveChangesAsync();

                // avoid Refreshing the POST Operation -> Redirect

                return RedirectToAction(nameof(Index));
                //return RedirectToAction("Index", "CategoryTypes", new { area = "Admin" });
            }
            else
            {
                // one can simply return to the Form View again for Correction
                return View(categoryTypes);
            }
        }

        // Get: /<controller>/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // search for the ID
            var categoryType = await _colibriDbContext.CategoryTypes.FindAsync(id);

            if (categoryType == null)
            {
                return NotFound();
            }
            return View(categoryType);
        }

        // Post: /<controller>/Edit
        // @param Category
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CategoryTypes categoryTypes)
        {
            // the IDs should be equal
            if (id != categoryTypes.Id)
            {
                return NotFound();
            }

            // Check the State Model Binding
            if (ModelState.IsValid)
            {
                // Update the Changes
                _colibriDbContext.Update(categoryTypes);
                await _colibriDbContext.SaveChangesAsync();

                // avoid Refreshing the POST Operation -> Redirect
                //return View("Details", newCategory);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                // one can simply return to the Form View again for Correction
                return View(categoryTypes);
            }
        }

        // Get: /<controller>/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // search for the ID
            var categoryType = await _colibriDbContext.CategoryTypes.FindAsync(id);

            if (categoryType == null)
            {
                return NotFound();
            }
            return View(categoryType);
        }

        // Get: /<controller>/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            // search for the ID
            var categoryType = await _colibriDbContext.CategoryTypes.FindAsync(id);

            if (categoryType == null)
            {
                return NotFound();
            }
            return View(categoryType);
        }

        // Post: /<controller>/Delete
        // @param Category
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var categoryType = await _colibriDbContext.CategoryTypes.FindAsync(id);

            _colibriDbContext.CategoryTypes.Remove(categoryType);

            // Update the Changes
            await _colibriDbContext.SaveChangesAsync();

            // avoid Refreshing the POST Operation -> Redirect
            //return View("Details", newCategory);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Index()
        {
            var categoryTypesList = _colibriDbContext.CategoryTypes.ToList();

            return View(categoryTypesList);
        }
    }
}

Colibri/Colibri/Areas/Admin/Views/CategoryTypes/Create.cshtml
@model Colibri.Models.CategoryTypes
@{
    ViewData["Title"] = "Create";
}

<h2 class="text-info">Create Category Type</h2>

<form method="post" asp-action="Create">
    <div class="p-4 border rounded">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" class="form-control" />
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Create" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Colibri/Colibri/Areas/Admin/Views/CategoryTypes/Delete.cshtml
@model Colibri.Models.CategoryTypes
@{
    ViewData["Title"] = "Delete";
}

<h2 class="text-info">Delete Category Type</h2>

<form method="post" asp-action="Delete">
    <div class="p-4 border rounded">
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" disabled class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-danger" asp-route-id="@Model.Id" value="Delete" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>

Colibri/Colibri/Areas/Admin/Views/CategoryTypes/Details.cshtml
@model Colibri.Models.CategoryTypes
@{
    ViewData["Title"] = "Details";
}

<h2 class="text-info">Category Type Details</h2>

<div class="p-4 border rounded">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group row">
        <div class="col-2">
            <label asp-for="Name"></label>
        </div>
        <div class="col-5">
            <input asp-for="Name" disabled class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </div>
</div>

Colibri/Colibri/Areas/Admin/Views/CategoryTypes/Edit.cshtml
@model Colibri.Models.CategoryTypes
@{
    ViewData["Title"] = "Edit";
}

<h2 class="text-info">Edit Category Type</h2>

<form method="post" asp-action="Edit">
    <div class="p-4 border rounded">
        <input type="hidden" asp-for="Id" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Name"></label>
            </div>
            <div class="col-5">
                <input asp-for="Name" class="form-control" />
            </div>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" asp-route-id="@Model.Id" value="Update" />
            <a asp-action="Index" class="btn btn-success">Back to List</a>
        </div>
    </div>
</form>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Colibri/Colibri/Areas/Admin/Views/CategoryTypes/Index.cshtml
@model IEnumerable<Colibri.Models.CategoryTypes>

<div class="row">
    <div class="col-6 text-center">
        <h2 class="text-info">Category Type List</h2>
    </div>
    <div class="col-6 text-right">
        <a asp-action="Create" asp-controller="CategoryTypes" class="btn btn-info"><i class="fas fa-plus"></i>&nbsp; New Category Type</a>
    </div>
</div>
<div>
    <table class="table table-striped border">
        <tr class="text-info">
            <th>
                @Html.DisplayNameFor(m => m.Name)
            </th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(m => item.Name)
                </td>
                <td>
                    <partial name="_TableButtonPartial" model="item.Id" />
                </td>
            </tr>
        }
    </table>
</div>