Colibri/Colibri/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Colibri
{
    [Route("about")]
    public class AboutController : Controller
    {
        // Phone
        [Route("")]
        public string Phone()
        {
            return "031 301 03 47";
        }

        // Address
        [Route("address")]
        public string Address()
        {
            return "CH";
        }
    }
}

Colibri/Colibri/Views/Shared/_AppointmentCustomerDetails.cshtml
@model Colibri.Models.Appointments

<!-- individual CSS -->
@section shoppingCart {
    <link href="~/css/shoppingCart.css" rel="stylesheet" />
}

<h4 class="text-success">Appointment Details</h4>

<div class="appointment-details container border">
    <!-- Part 1 -->
    <div class="col-12">
        <div class="row">
            <div class="col-2">
                Full Name
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerName" readonly class="form-control" />
            </div>
            <!-- empty row -->
            <div class="col-2"></div>

            <div class="col-2">
                Email
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerEmail" readonly class="form-control" />
            </div>
        </div>
    </div>
    <!-- END: Part 1 -->
    <!-- Part 2 -->
    <div class="col-12">
        <div class="row">
            <div class="col-2">
                Phone Number
            </div>
            <div class="col-3">
                <input asp-for="@Model.CustomerPhoneNumber" readonly class="form-control" />
            </div>
            <!-- empty row -->
            <div class="col-2"></div>

            <div class="col-2">
                Appointment Date
            </div>
            <div class="col-3">
                <input asp-for="@Model.AppointmentDate" readonly class="form-control" />
            </div>
        </div>
    </div>
    <!-- END: Part 2 -->
</div>

Colibri/Colibri/Views/Shared/_AppointmentProductDetails.cshtml
@model List<Colibri.Models.Products>

<!-- individual CSS -->
@section appointments {
    <link href="~/css/appointments.css" rel="stylesheet" />
}

@if (Model.Count > 0)
{
    <div class="appointment-product-details">
        <table class="table table-striped">
            <tr class="table-info">

                <!-- Table Headers -->
                <th id="imageRowHeader"></th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().Name"></label>
                </th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().Price"></label>
                </th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().CategoryTypes"></label>
                </th>
                <th>
                    <label asp-for="@Model.FirstOrDefault().Description"></label>
                </th>
                <th></th>
                <!-- END: Table Headers -->
            </tr>

            <!-- Table Content -->
            @foreach (var item in Model)
            {
                <!-- Images clickable: redirect to Details Page -->
                <tr class="table-content">
                    <td id="imageContent">
                        <a asp-area="Customer" asp-controller="ProductsHome" asp-action="Details" asp-route-id="@item.Id">
                            <img src="@item.Image" />
                        </a>
                    </td>
                    <td class="tableContentColumn">
                        @Html.DisplayFor(p => item.Name)
                    </td>
                    <td class="tableContentColumn">
                        @Html.DisplayFor(p => item.Price)
                    </td>
                    <td class="tableContentColumn">
                        @Html.DisplayFor(p => item.CategoryTypes.Name)
                    </td>
                    <td class="tableContentColumn">
                        @Html.DisplayFor(p => item.Description)
                    </td>
                </tr>
            }
        </table>
    </div>
}
else
{
    <div>No Items added!</div>
}

Colibri/Colibri/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Colibri.Extensions
@using Colibri.Utility

@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
        <!-- Date and Time Pickers -->
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <!-- Custom CSS -->
        <link href="~/css/index.css" rel="stylesheet" />
        <link href="~/css/products.css" rel="stylesheet" />
        <!-- individual CSS -->
        @RenderSection("shoppingCart", false)
        @RenderSection("appointments", false)
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
        <!-- Date and Time Pickers -->
        <link rel="stylesheet" href="~/css/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <!-- Custom CSS -->
        <link href="~/css/index.css" rel="stylesheet" />
        <link href="~/css/products.css" rel="stylesheet" />
        <!-- individual CSS -->
        @RenderSection("shoppingCart", false)
        @RenderSection("appointments", false)
    </environment>

</head>
<body>
    <header class="container">
        <nav class="navbar navbar-dark bg-dark navbar-expand-md">
            <h1 class="navbar-brand"><i class="fa fa-globe"></i> Colibri</h1>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#theMenu">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="theMenu" class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                    </li>

                    <!-- hide if not authorized -->
                    @if (User.IsInRole(StaticDetails.SuperAdminEndUser))
                    {

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="CategoryTypes" asp-action="Index">Category Types</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">Special Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="AdminUsers" asp-action="Index">Admin Users</a>
                        </li>
                    }

                    @if (User.IsInRole(StaticDetails.SuperAdminEndUser) || User.IsInRole(StaticDetails.AdminEndUser))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Appointments" asp-action="Index">Appointments</a>
                        </li>
                    }

                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="ProductsHome" asp-action="Index">Products List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="Customer" asp-controller="About" asp-action="">About</a>
                    </li>
                    @*@if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }*@

                    <!-- handle Session: Values in the Session -->
                    @if (HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart") != null)
                    {
                        <li style="color:white">
                            <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp;
                                <!-- # Items in the Shopping Cart -->
                                @{
                                    var count = HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart").Count;
                                }
                                (@count)
                            </a>
                        </li>
                    }
                    else
                    {
                        <li style="color:white">
                            <a asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp;
                                <!-- display Zero -->
                                (0)
                            </a>
                        </li>
                    }
                </ul>
                <div class="navbar-right">
                    @*<vc:login-logout></vc:login-logout>*@
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <main class="container">
        <aside></aside>
        <section>
            <article>
                <h2 class="text-center">@ViewBag.Title</h2>
                @RenderBody()
            </article>
        </section>
    </main>
    <footer class="container">
        <div class="text-center">
            Colibri @DateTime.Now.Year
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <!-- asp-append-version  -->
        <script src="~/js/index.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <!-- asp-append-version  -->
        <script src="~/js/index.js" asp-append-version="true"></script>
        <script src="~/js/jquery-ui.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", false)
</body>
</html>

Colibri/Colibri/Views/Shared/_TableButtonPartial.cshtml
@model int

<td style="width:150px">
    <div class="btn-group" role="group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit/"+Model)">
            <i class="fas fa-edit"></i>
        </a>
        <a type="button" class="btn btn-success" href="@Url.Action("Details/"+Model)">
            <i class="far fa-list-alt"></i>
        </a>
        <a type="button" class="btn btn-danger" href="@Url.Action("Delete/"+Model)">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>